### ISSUE TITLE
Supermarket.chef.io

### ISSUE THREAD

**Issue by andytson** [elvetemedve/mailcatcher#2]
I was wondering if you could consider calling this cookbook mailcatcher-ng, and publish it to supermarket.chef.io?

Using git for 3rd party cookbooks is nasty and doesn't allow semver versioning. Also there's not full confidence a version wont change unlike git tags.

**Comment by elvetemedve** [comment]
I agree that this is not the best place to host the cookbook.

What is the "ng" supposed to mean in `mailcatcher-ng`? I would rather call it `mailcatcher-php`, since it contains configuration for PHP.

**Comment by andytson** [comment]
next-gen, as in better than the one called mailcatcher on there.

I'm going to contribute a PR when I can to add add a postfix recipe for a more generic implementation

**Comment by elvetemedve** [comment]
It's done (see https://supermarket.chef.io/cookbooks/mailcatcher-ng).
